### ISSUE TITLE
autoreq IndexError

### ISSUE THREAD

**Issue by cloverhsc** [lucemia/auto-requirements#4]
### First something not good on use:
- I get this tool from _Taiwan Python Meetup (2016-03-08)_.
- After I use **pip install autoreq**. It can't run because we need install panda, html5lib, clime, lxml packages. So clone this project and use **pip install -r requirement.txt**  . But when install **xml** it will failed. So google msg and get  **apt-get install libxml2-dev libxslt1-dev python-dev python-lxml** for compiler lxml. 
- After dependence. When I try **autoreq -i my_requirement.txt** . It failed again and msg about "from bs4 import BeautifulSoup" so I **pip install beautifulsoup4** . Now It's all down then to use on my requirements.txt. **It failed again .....**

---
#### This my requirement file contents.(use pip freeze):

![req](https://cloud.githubusercontent.com/assets/6084882/13768266/ec53899c-eaae-11e5-9988-cd76b0a7c15c.png)
#### Error msg:

![ermsg](https://cloud.githubusercontent.com/assets/6084882/13768291/3f3a82a0-eaaf-11e5-9218-fa199d6f7b47.png)
#### My environments.:
- Kubuntu 15.10
- Python 2.7.10

Thanks.

**Comment by lucemia** [comment]
thanks your report, 
Would you please attach the origin requirements file to me, therefore I can check

I will make autoreq easier to install in next release (probably this Friday) #5

**Comment by cloverhsc** [comment]
Hi lucemia :

 This is my requirement file. 

THX.
[requirement.txt](https://github.com/lucemia/autoreq/files/173301/requirement.txt)

**Comment by cloverhsc** [comment]
Hi 你好：
剛剛經由同事測試應該是81行的regular 有錯誤，因為我的requirement內有個path.py這個package. 
藉由try except 中發現，當程式跑到這行的時候有印出錯誤。但是其他的package會pass。提供你作參考。
謝謝。

**Comment by lucemia** [comment]
thanks your report, 
已經推了一版修正過的版本

please try 
`pip install autoreq --no-cache -U` 
後這個 bug 是否還在

Thanks your report!

**Comment by cloverhsc** [comment]
剛剛測試的結果是 ok的。
新的版本目前看起來沒問題。

**Comment by lucemia** [comment]
thanks
